let byWrap = document.getElementsByTagName("div").namedItem("wrap");
let byFormGroup = document.getElementsByTagName("div").namedItem("form-group");
let label1 = document.getElementsByTagName("label").namedItem("label1");
let label2 = document.getElementsByTagName("label").namedItem("label2");
let label3 = document.getElementsByTagName("label").namedItem("label3");
let label4 = document.getElementsByTagName("label").namedItem("label4");
let label5 = document.getElementsByTagName("label").namedItem("label5");
let label6 = document.getElementsByTagName("label").namedItem("label6");
let label7 = document.getElementsByTagName("label").namedItem("label7");
let label8 = document.getElementsByTagName("label").namedItem("label8");
let label9 = document.getElementsByTagName("label").namedItem("label9");
let label10 = document.getElementsByTagName("label").namedItem("label10");
let label11= document.getElementsByTagName("label").namedItem("label12");
let label13= document.getElementsByTagName("label").namedItem("label13");
let label14= document.getElementsByTagName("label").namedItem("label14");
let label15= document.getElementsByTagName("label").namedItem("label15");
let label16= document.getElementsByTagName("label").namedItem("label16");
let label17= document.getElementsByTagName("label").namedItem("label17");
let label18= document.getElementsByTagName("label").namedItem("label18");
let label19= document.getElementsByTagName("label").namedItem("label19");
let input1 = document.getElementsByTagName("input").namedItem("firstName")
let input2 = document.getElementsByTagName("input").namedItem("lastname")
let input3 = document.getElementsByTagName("input").namedItem("email")
let input4 = document.getElementsByTagName("input").namedItem("premail")
let input5 = document.getElementsByTagName("input").namedItem("password")
let input6 = document.getElementsByTagName("input").namedItem("color")
let input7 = document.getElementsByTagName("input").namedItem("week")
let input8 = document.getElementsByTagName("input").namedItem("motnh")
let input9 = document.getElementsByTagName("input").namedItem("date")
let input10 = document.getElementsByTagName("input").namedItem("time")
let input11 = document.getElementsByTagName("input").namedItem("inputas")
let input12 = document.getElementsByTagName("input").namedItem("ha")
let input13 = document.getElementsByTagName("input").namedItem("yoq")
let input14 = document.getElementsByTagName("input").namedItem("bilmadim")
let input15 = document.getElementsByTagName("input").namedItem("ha2")
let input16 = document.getElementsByTagName("input").namedItem("yoq2")
let input17 = document.getElementsByTagName("input").namedItem("bilmadim2")
let select1 = document.getElementsByTagName("select").namedItem("age")
let select2 = document.getElementsByTagName("select").namedItem("day")
let select3 = document.getElementsByTagName("select").namedItem("oy")
let select4 = document.getElementsByTagName("select").namedItem("year")



byWrap.style.width = "1200px";
byWrap.style.margin = "0 auto";

byFormGroup.style.width = "720px";
byFormGroup.style.margin = "0 auto";
byFormGroup.style.boxShadow = "0 0 10px rgba(80, 80, 80, 0.5)";
byFormGroup.style.padding = "1rem 1.5rem";
byFormGroup.style.boxSizing = "border-box";

label1.style.width = "35%";
label1.style.padding = "0.5rem 1.5rem";
label1.style.boxSizing = "border-box";
label1.style.display = "inline-block";
label1.style.marginBottom = "10px";
label1.style.textAlign = "right";

label2.style.width = "35%";
label2.style.padding = "0.5rem 1.5rem";
label2.style.boxSizing = "border-box";
label2.style.display = "inline-block";
label2.style.marginBottom = "10px";
label2.style.textAlign = "right";

label3.style.width = "35%";
label3.style.padding = "0.5rem 1.5rem";
label3.style.boxSizing = "border-box";
label3.style.display = "inline-block";
label3.style.marginBottom = "10px";
label3.style.textAlign = "right";

label4.style.width = "35%";
label4.style.padding = "0.5rem 1.5rem";
label4.style.boxSizing = "border-box";
label4.style.display = "inline-block";
label4.style.marginBottom = "10px";
label4.style.textAlign = "right";

label5.style.width = "35%";
label5.style.padding = "0.5rem 1.5rem";
label5.style.boxSizing = "border-box";
label5.style.display = "inline-block";
label5.style.marginBottom = "10px";
label5.style.textAlign = "right";

label6.style.width = "35%";
label6.style.padding = "0.5rem 1.5rem";
label6.style.boxSizing = "border-box";
label6.style.display = "inline-block";
label6.style.marginBottom = "10px";
label6.style.textAlign = "right";
 
label7.style.width = "35%";
label7.style.padding = "0.5rem 1.5rem";
label7.style.boxSizing = "border-box";
label7.style.display = "inline-block";
label7.style.marginBottom = "10px";
label7.style.textAlign = "right";
 
label8.style.width = "35%";
label8.style.padding = "0.5rem 1.5rem";
label8.style.boxSizing = "border-box";
label8.style.display = "inline-block";
label8.style.marginBottom = "10px";
label8.style.textAlign = "right";
 
label9.style.width = "35%";
label9.style.padding = "0.5rem 1.5rem";
label9.style.boxSizing = "border-box";
label9.style.display = "inline-block";
label9.style.marginBottom = "10px";
label9.style.textAlign = "right";
 
label10.style.width = "35%";
label10.style.padding = "0.5rem 1.5rem";
label10.style.boxSizing = "border-box";
label10.style.display = "inline-block";
label10.style.marginBottom = "10px";
label10.style.textAlign = "right";
 
label11.style.width = "35%";
label11.style.padding = "0.5rem 1.5rem";
label11.style.boxSizing = "border-box";
label11.style.display = "inline-block";
label11.style.marginBottom = "10px";
label11.style.textAlign = "right";
 
label12.style.width = "35%";
label12.style.padding = "0.5rem 1.5rem";
label12.style.boxSizing = "border-box";
label12.style.display = "inline-block";
label12.style.marginBottom = "10px";
label12.style.textAlign = "right";
 
label13.style.width = "35%";
label13.style.padding = "0.5rem 1.5rem";
label13.style.boxSizing = "border-box";
label13.style.display = "inline-block";
label13.style.marginBottom = "10px";
label13.style.textAlign = "right";
 
label14.style.width = "35%";
label14.style.padding = "0.5rem 1.5rem";
label14.style.boxSizing = "border-box";
label14.style.display = "inline-block";
label14.style.marginBottom = "10px";
label14.style.textAlign = "right";
 
label15.style.width = "35%";
label15.style.padding = "0.5rem 1.5rem";
label15.style.boxSizing = "border-box";
label15.style.display = "inline-block";
label15.style.marginBottom = "10px";
label15.style.textAlign = "right";
 
label16.style.width = "35%";
label16.style.padding = "0.5rem 1.5rem";
label16.style.boxSizing = "border-box";
label16.style.display = "inline-block";
label16.style.marginBottom = "10px";
label16.style.textAlign = "right";
 
label17.style.width = "35%";
label17.style.padding = "0.5rem 1.5rem";
label17.style.boxSizing = "border-box";
label17.style.display = "inline-block";
label17.style.marginBottom = "10px";
label17.style.textAlign = "right";
 
label18.style.width = "35%";
label18.style.padding = "0.5rem 1.5rem";
label18.style.boxSizing = "border-box";
label18.style.display = "inline-block";
label18.style.marginBottom = "10px";
label18.style.textAlign = "right";
 
label19.style.width = "35%";
label19.style.padding = "0.5rem 1.5rem";
label19.style.boxSizing = "border-box";
label19.style.display = "inline-block";
label19.style.marginBottom = "10px";
label19.style.textAlign = "right";

input1.style.width = "60%"
input1.style.padding = "0.5rem 1.5rem"
input1.style.boxSizing = "border-box"
input1.style.border = "1px solid #cccccc"
input1.style.borderRadius ="5px"
input1.style.display = "inline block"
input1.style.marginBottom = "10px"

input2.style.width = "60%"
input2.style.padding = "0.5rem 1.5rem"
input2.style.boxSizing = "border-box"
input2.style.border = "1px solid #cccccc"
input2.style.borderRadius ="5px"
input2.style.display = "inline block"
input2.style.marginBottom = "10px"

input3.style.width = "60%"
input3.style.padding = "0.5rem 1.5rem"
input3.style.boxSizing = "border-box"
input3.style.border = "1px solid #cccccc"
input3.style.borderRadius ="5px"
input3.style.display = "inline block"
input3.style.marginBottom = "10px"

input4.style.width = "60%"
input4.style.padding = "0.5rem 1.5rem"
input4.style.boxSizing = "border-box"
input4.style.border = "1px solid #cccccc"
input4.style.borderRadius ="5px"
input4.style.display = "inline block"
input4.style.marginBottom = "10px"

input5.style.width = "60%"
input5.style.padding = "0.5rem 1.5rem"
input5.style.boxSizing = "border-box"
input5.style.border = "1px solid #cccccc"
input5.style.borderRadius ="5px"
input5.style.display = "inline block"
input5.style.marginBottom = "10px"

input6.style.width = "60%"
input6.style.padding = "0.5rem 1.5rem"
input6.style.boxSizing = "border-box"
input6.style.border = "1px solid #cccccc"
input6.style.borderRadius ="5px"
input6.style.display = "inline block"
input6.style.marginBottom = "10px"

input7.style.width = "60%"
input7.style.padding = "0.5rem 1.5rem"
input7.style.boxSizing = "border-box"
input7.style.border = "1px solid #cccccc"
input7.style.borderRadius ="5px"
input7.style.display = "inline block"
input7.style.marginBottom = "10px"

input8.style.width = "60%"
input8.style.padding = "0.5rem 1.5rem"
input8.style.boxSizing = "border-box"
input8.style.border = "1px solid #cccccc"
input8.style.borderRadius ="5px"
input8.style.display = "inline block"
input8.style.marginBottom = "10px"

input9.style.width = "60%"
input9.style.padding = "0.5rem 1.5rem"
input9.style.boxSizing = "border-box"
input9.style.border = "1px solid #cccccc"
input9.style.borderRadius ="5px"
input9.style.display = "inline block"
input9.style.marginBottom = "10px"

input10.style.width = "60%"
input10.style.padding = "0.5rem 1.5rem"
input10.style.boxSizing = "border-box"
input10.style.border = "1px solid #cccccc"
input10.style.borderRadius ="5px"
input10.style.display = "inline block"
input10.style.marginBottom = "10px"

input11.style.width = "60%"
input11.style.padding = "0.5rem 1.5rem"
input11.style.boxSizing = "border-box"
input11.style.border = "1px solid #cccccc"
input11.style.borderRadius ="5px"
input11.style.display = "inline block"
input11.style.marginBottom = "10px"

input12.style.width = "60%"
input12.style.padding = "0.5rem 1.5rem"
input12.style.boxSizing = "border-box"
input12.style.border = "1px solid #cccccc"
input12.style.borderRadius ="5px"
input12.style.display = "inline block"
input12.style.marginBottom = "10px"

input13.style.width = "60%"
input13.style.padding = "0.5rem 1.5rem"
input13.style.boxSizing = "border-box"
input13.style.border = "1px solid #cccccc"
input13.style.borderRadius ="5px"
input13.style.display = "inline block"
input13.style.marginBottom = "10px"

input14.style.width = "60%"
input14.style.padding = "0.5rem 1.5rem"
input14.style.boxSizing = "border-box"
input14.style.border = "1px solid #cccccc"
input14.style.borderRadius ="5px"
input14.style.display = "inline block"
input14.style.marginBottom = "10px"

input15.style.width = "60%"
input15.style.padding = "0.5rem 1.5rem"
input15.style.boxSizing = "border-box"
input15.style.border = "1px solid #cccccc"
input15.style.borderRadius ="5px"
input15.style.display = "inline block"
input15.style.marginBottom = "10px"

input16.style.width = "60%"
input16.style.padding = "0.5rem 1.5rem"
input16.style.boxSizing = "border-box"
input16.style.border = "1px solid #cccccc"
input16.style.borderRadius ="5px"
input16.style.display = "inline block"
input16.style.marginBottom = "10px"

input17.style.width = "60%"
input17.style.padding = "0.5rem 1.5rem"
input17.style.boxSizing = "border-box"
input17.style.border = "1px solid #cccccc"
input17.style.borderRadius ="5px"
input17.style.display = "inline block"
input17.style.marginBottom = "10px"

select1.style.width = "30%"
select1.style.display = "inline block"
select1.style.borderRadius ="5px"
select1.style.color = "#ffffff"
select1.style.width = "200px"

select2.style.width = "30%"
select2.style.display = "inline block"
select2.style.borderRadius ="5px"
select2.style.color = "#ffffff"
select2.style.width = "200px"

select3.style.width = "30%"
select3.style.display = "inline block"
select3.style.borderRadius ="5px"
select3.style.color = "#ffffff"
select3.style.width = "200px"

select4.style.width = "30%"
select4.style.display = "inline block"
select4.style.borderRadius ="5px"
select4.style.color = "#ffffff"
select4.style.width = "200px"